packaging_format = 2

id = "wekan"
name = "Wekan"
description.en = "Trello-like kanban"
description.fr = "Kanban similaire à Trello"

version = "7.48~ynh1"

maintainers = ["alexAubin", "ljf", "yalh76"]

[upstream]
license = "MIT"
website = "https://wekan.github.io"
demo = "https://demo.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h"
admindoc = "https://github.com/wekan/wekan/wiki"
code = "https://github.com/wekan/wekan"

[integration]
yunohost = ">= 11.2.12"
architectures = ["amd64"]
multi_instance = true

ldap = true

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wekan"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        amd64.url = "https://github.com/wekan/wekan/releases/download/v7.48/wekan-7.48-amd64.zip"
        amd64.sha256 = "69bc47a5c493d5e585ed5654d1cf24b7570a916a45c99d4b0b652b51ec77dfb5"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = ".*-amd64.zip"

    [resources.ports]

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    #admin.allowed = "admins"
